baseURL = 'https://lollipop-27.github.io/my-blog/'
locale = 'en-gb'
title = 'My Blog'

[module]
  [[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v4"

[params]
  description = "My UAL UX Design homework blog."

  [menu]

  [[menu.main]]
    identifier = "weeks"
    name = "Weeks"
    url = "/weeks/"
    weight = 10